### ISSUE TITLE
Need support for a 'sketch' theme in the ui urlParameter

### ISSUE THREAD

**Issue by puru1761** [marcveens/react-drawio#13]
Hi,

Thank you for this great package. I was looking over the draw.io themes documentation, and it seems that the 'sketch' theme mentioned there is not supported for this package. The supported themes seem to be 'dark' | 'kenedy' | 'atlas' | 'min'. Would it be possible to add a 'sketch' theme to support this theme from draw.io?

https://www.drawio.com/blog/diagram-editor-theme

Thanks,
Puru

**Comment by marcveens** [comment]
Hi @puru1761, good one! I just published a new version with all supported themes. 

https://github.com/marcveens/react-drawio/blob/d82b25bd90eedd07b241e228a7f7bce01819592a/src/types.ts#L34
