### ISSUE TITLE
Unable to disable 'Save & Exit' button

### ISSUE THREAD

**Issue by puru1761** [marcveens/react-drawio#16]
Hi Marc,

I am attempting to disable the save and exit button (and all other buttons). Per your documentation this can be achieved by
setting:

```lang="ts"
<DrawIoEmbed
  urlParameters={{
    noExitBtn: true,
    noSaveBtn: true,
    saveAndExit: false,
  }}
/>
```

However, on doing this, I still see the save & exit button:

![image](https://github.com/marcveens/react-drawio/assets/32076726/c595051f-249e-400f-997b-2bb63cfe9e5f)

Is this a bug, and if so, could you please consider fixing it when you get the time?

Thanks,
Puru

**Comment by marcveens** [comment]
Thanks for reporting this issue. It's fixed in version 0.1.5 which is released just now
