### ISSUE TITLE
Programmatically call the save event

### ISSUE THREAD

**Issue by AngusParsonson** [marcveens/react-drawio#23]
Is it possible to programmatically trigger the save event?

**Comment by marcveens** [comment]
You can programmatically trigger the export event, as shown at https://github.com/marcveens/react-drawio?tab=readme-ov-file#export-diagram-programmatically. That's actually the only related action provided by [drawio](https://www.drawio.com/doc/faq/embed-mode), but that should do, right?

**Comment by AngusParsonson** [comment]
Hi @marcveens, it wasn't quite what I needed but have managed to make it work. Cheers.
