### ISSUE TITLE
Configuration makes the implementation fail

### ISSUE THREAD

**Issue by pzehle** [marcveens/react-drawio#24]
Just adding the `configuration` tag to the component makes the embedded iframe to just be blank. Adding or removing any options to the object makes no difference:

```jsx
<DrawIoEmbed
	urlParameters={{
		ui: 'min',
		spin: true,
		saveAndExit: false,
		noSaveBtn: true,
		noExitBtn: true,
	}}
	configuration={{}}
/>
```

Removing the `configuration` tag makes it load correctly. Am I doing something wrong?

**Comment by marcveens** [comment]
Perhaps it's better to make the `configuration` option `undefined` if it's not used. Does that help?

**Comment by pzehle** [comment]
The problem is not actually that, the problem is that I DO want to send configurations to it, since I want to allow only the use of UML libraries.

**Comment by marcveens** [comment]
In Storybook there a working demo where `urlParameters`, `xml` and `configurations` are combined: https://marcveens.github.io/react-drawio/?path=/story/components-drawioembed--with-configurations (and the [code](https://github.com/marcveens/react-drawio/blob/5e6daceb9947e5fb22f4f4df206c25e9d396f697/stories/DiagramsEmbed.stories.tsx#L85)). 

If that still doesn't help, could you provide working example using Stackblitz for example so I can have a look?
