### ISSUE TITLE
Add autosave action

### ISSUE THREAD

**Issue by AMV1909** [marcveens/react-drawio#35]
It is possible to add autosave action?

https://www.drawio.com/doc/faq/embed-mode#description-of-the-json-protocol

**Comment by marcveens** [comment]
But of course! Update your package and you have the `autosave` property available now. Whenever a change is made, `onAutoSave` is triggered.

See it in action on the pubished Storybook demo: https://marcveens.github.io/react-drawio/?path=/story/components-drawioembed--auto-save

**Comment by AMV1909** [comment]
Thank you kindly
